# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 20:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Developmet_group', '0001_initial'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Tools',
            fields=[
                ('Business', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Platform', models.CharField(max_length=100)),
                ('API', models.CharField(max_length=100)),
                ('URL_Platform', models.URLField(max_length=300)),
                ('User', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Aplication_log',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Estate', models.CharField(choices=[('1', 'En desarrollo'), ('2', 'En producción'), ('3', 'Indefinido'), ('4', 'Concluido')], max_length=50)),
                ('State_Store', models.CharField(blank=True, choices=[('1', 'Publicada'), ('2', 'En Proceso'), ('3', 'En certificación'), ('4', 'Eliminada'), ('5', 'Indefinido')], max_length=100, null=True)),
                ('URL_store', models.URLField(blank=True, max_length=300, null=True)),
                ('Console_Developer', models.URLField(blank=True, max_length=300, null=True)),
                ('Type_app', models.CharField(max_length=100)),
                ('Device', models.CharField(blank=True, max_length=100, null=True)),
                ('Monetization', models.CharField(blank=True, max_length=100, null=True)),
                ('Photo1', models.ImageField(blank=True, null=True, upload_to='media/Image')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='media/Image')),
                ('Photo3', models.ImageField(blank=True, null=True, upload_to='media/Image')),
                ('Photo4', models.ImageField(blank=True, null=True, upload_to='media/Image')),
                ('Key_project', models.CharField(blank=True, max_length=100, null=True)),
                ('URL_VCS', models.URLField(blank=True, max_length=300, null=True)),
                ('Packages', models.FileField(blank=True, null=True, upload_to='media/Packges')),
                ('Description', ckeditor.fields.RichTextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resouces_tools',
            fields=[
                ('Means', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Utility', models.CharField(max_length=100)),
                ('URL_tools', models.URLField(max_length=300)),
                ('User', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Type_app', models.CharField(max_length=100)),
                ('Commentary', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('Store', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('URL_store', models.URLField(blank=True, max_length=300, null=True)),
                ('Commentary', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_client',
            fields=[
                ('Client', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('URL_client', models.URLField(blank=True, max_length=300, null=True)),
                ('Commentary', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VCS',
            fields=[
                ('VCS', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('URL_VCS', models.URLField(max_length=300)),
                ('User', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin_app',
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Aplication_log6', serialize=False, to='admin_app.Aplication_log')),
                ('Estate', models.CharField(choices=[('1', 'En desarrollo'), ('2', 'En producción'), ('3', 'Indefinido'), ('4', 'Concluido')], max_length=100)),
                ('Device', models.CharField(blank=True, max_length=100, null=True)),
                ('URL_VCS', models.URLField(blank=True, max_length=300, null=True)),
                ('Packages', models.FileField(blank=True, null=True, upload_to='media/Packages')),
                ('Type_app', models.CharField(max_length=100)),
                ('Date_start', models.DateTimeField()),
                ('Data_finish', models.DateTimeField()),
                ('Records_note', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('API', models.ManyToManyField(related_name='Aplication_log11', to='admin_app.API_Tools')),
                ('Client', models.ManyToManyField(related_name='Aplication_log7', to='admin_app.Shop_client')),
                ('Group_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Developmet_group.Developmet_group')),
                ('Store', models.ManyToManyField(related_name='Aplication_log8', to='admin_app.Shop')),
                ('VCS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Aplication_log10', to='admin_app.VCS')),
            ],
        ),
        migrations.AddField(
            model_name='aplication_log',
            name='API',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aplication_log4', to='admin_app.API_Tools'),
        ),
        migrations.AddField(
            model_name='aplication_log',
            name='Client',
            field=models.ManyToManyField(related_name='Shop_client2', to='admin_app.Shop_client'),
        ),
        migrations.AddField(
            model_name='aplication_log',
            name='Group_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Developmet_group.Developmet_group'),
        ),
        migrations.AddField(
            model_name='aplication_log',
            name='Means',
            field=models.ManyToManyField(to='admin_app.Resouces_tools'),
        ),
        migrations.AddField(
            model_name='aplication_log',
            name='Store',
            field=models.ManyToManyField(related_name='Shopclient1', to='admin_app.Shop'),
        ),
        migrations.AddField(
            model_name='aplication_log',
            name='VCS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Aplication_log5', to='admin_app.VCS'),
        ),
    ]
