# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 20:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('Developer', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Specialty', models.CharField(max_length=100)),
                ('Technology', models.CharField(max_length=200)),
                ('Development_tool', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=200)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/image')),
                ('Descrition', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developmet_group',
            fields=[
                ('Name_goup', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Descrition', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Analiyst', models.OneToOneField(help_text='En este campo seleccione el nombre del desarrollado que estará a cargo de el equipo de desarrollo', on_delete=django.db.models.deletion.CASCADE, related_name='Developmet1', to='Developmet_group.Developer')),
                ('Dveloper1', models.OneToOneField(help_text='En este campo seleccione el nombre del desarrollado que ocupará esta posición en el equipo de desarrollo', on_delete=django.db.models.deletion.CASCADE, related_name='Developmet2', to='Developmet_group.Developer')),
                ('Dveloper2', models.OneToOneField(blank=True, help_text='En este campo seleccione el nombre del desarrollado que ocupará esta posición en el equipo de desarrollo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Developmet3', to='Developmet_group.Developer')),
                ('Dveloper3', models.OneToOneField(blank=True, help_text='En este campo seleccione el nombre del desarrollado que ocupará esta posición en el equipo de desarrollo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Developmet4', to='Developmet_group.Developer')),
                ('Dveloper4', models.OneToOneField(blank=True, help_text='En este campo seleccione el nombre del desarrollado que ocupará esta posición en el equipo de desarrollo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Developmet5', to='Developmet_group.Developer')),
                ('Dveloper5', models.OneToOneField(blank=True, help_text='En este campo seleccione el nombre del desarrollado que ocupará esta posición en el equipo de desarrollo ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Developmet6', to='Developmet_group.Developer')),
                ('Dveloper6', models.ManyToManyField(help_text='Si su grupo de desarrollo es muy grande puede  utilizar este campo para agregar una cantidad de ilimitada de miembros a su grupo de desarrollo  ', related_name='Developmet7', to='Developmet_group.Developer')),
            ],
        ),
    ]
